### ISSUE TITLE
Is this module alive?

### ISSUE THREAD

**Issue by reyiyo** [senecajs/seneca-auth#22]
I'm facing the same problem as in #20 and there is no answer for any open issues. Is this module going to be fixed/maintained?

**Comment by iantocristian** [comment]
Which version are you using?

**Comment by rjrodger** [comment]
0.5.0 is currently under active development, but is a fairly major refactor

**Comment by AdrieanKhisbe** [comment]
@rjrodger, should it be close, nope? :)
(by the way, what is still blocking the 0.5 realease)

**Comment by AdrieanKhisbe** [comment]
> $ touch this

**Comment by mirceaalexandru** [comment]
We are working on this module, so soon there will be a npm publish.

Closing this, if still an issue we can re-open
