### ISSUE TITLE
Use code as asserter

### ISSUE THREAD

**Issue by AdrieanKhisbe** [senecajs/seneca-auth#54]
Would anyone oppose a refactor to rely on `code` expects rather than assert in all the tests?

(I volounter for the change an dPR)

**Comment by floridemai** [comment]
@AdrieanKhisbe better leave this opened here for a while as this was part of a bigger refactor. I'll ping some people around to see about it.
Not sure, but probably we should look into writing more tests. Does those cover everything? :)

**Comment by AdrieanKhisbe** [comment]
by *"those"*, you mean current tests, or [code](https://github.com/hapijs/code)

**Comment by AdrieanKhisbe** [comment]
for coverage, now we know with [PR](https://github.com/senecajs/seneca-auth/pull/53).

about cover, 84%:  https://coveralls.io/github/AdrieanKhisbe/seneca-auth

**Comment by mihaidma** [comment]
@mirceaalexandru applied for maintainer. He has the 0.5.0 branch with a lot of fixes and tests.
@AdrieanKhisbe @floridemai 
Please don't do any work on auth until all stuff is updated and merged (3 forks/branches to be merged). It might take 1-2 more days

**Comment by AdrieanKhisbe** [comment]
@mihaidma can I launch the operation now?

**Comment by mihaidma** [comment]
Officially we move to Code, feel free to launch the operation :)

**Comment by AdrieanKhisbe** [comment]
> roger that
