### ISSUE TITLE
Merge branches/forks into seneca-auth

### ISSUE THREAD

**Issue by mihaidma** [senecajs/seneca-auth#56]
There is a branch to be merged:
https://github.com/senecajs/seneca-auth/tree/0.5.0
This branch has also tests.

An old fork with fixes, needed to check if anything useful:
https://github.com/floridemai/seneca-auth/commits/master

A recent fork with linting and Lab, some of it can be reused:
https://github.com/mihaidma/seneca-auth

**Comment by AdrieanKhisbe** [comment]
seems like it's now done )

**Comment by mihaidma** [comment]
step 3 is in progress, not done yet

**Comment by AdrieanKhisbe** [comment]
my bad :)

**Comment by mihaidma** [comment]
finished

**Comment by AdrieanKhisbe** [comment]
( @mihaidma : relaunch travis build: they seems to have build because of failed npm install. )

**Comment by mihaidma** [comment]
(@AdrieanKhisbe i'm on it. probably I'll update the package dependencies)

**Comment by AdrieanKhisbe** [comment]
(it look like just a refresh might do it.
I checked, Lodash is defined for sure :))

**Comment by mihaidma** [comment]
(it seems that a refresh doesn't solve it)
