### ISSUE TITLE
Could not find any {role:'user', get:'user'} action

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [senecajs/seneca-auth#67]
Hi, i am trying to make latest version of seneca-auth working with seneca-google-auth.

Sofar i get the following error
No matching action pattern found for { role: 'user', get: 'user', google_id: '3495723894534' }

But i could not find such action in seneca-user plugin.

Any hints where to look for it?

**Comment by mirceaalexandru** [comment]
@andriy-zhelvachenko seneca-user and seneca-auth are under tests and will be published hopefully this week. It will also contain support for Hapi.

Let me know if it is an emergency for your project or you can wait until those are published.

**Comment by andriy-zhelvachenko** [comment]
@mirceaalexandru , tnx for the quick reply. I can wait few weeks.

It would be good if you closed the issue below when done
https://github.com/senecajs/seneca-auth/issues/66

**Comment by mirceaalexandru** [comment]
@andriy-zhelvachenko great, I will
