### ISSUE TITLE
facebook authentication is broken

### ISSUE THREAD

**Issue by floridemai** [senecajs/seneca-auth#8]
facebook callback url times out

**Comment by AdrieanKhisbe** [comment]
> $ touch this || close

**Comment by mirceaalexandru** [comment]
This is part of current work, so it will be closed soon.

**Comment by AdrieanKhisbe** [comment]
@mirceaalexandru, how can I hep you? :)

**Comment by mirceaalexandru** [comment]
@AdrieanKhisbe in this moment we need to do a PR merge and some more tests, so for now I think you cannot help us here as work is almost done. 

Thank You

**Comment by AdrieanKhisbe** [comment]
Okey dokey. :smiley: 
By chance, any idea when it will be completed?

**Comment by AdrieanKhisbe** [comment]
@mirceaalexandru: have a look to [PR](https://github.com/senecajs/seneca-auth/pull/53) 
might be helpful to complete 0.5

**Comment by mirceaalexandru** [comment]
@AdrieanKhisbe yes, those are great, thank you.

**Comment by AdrieanKhisbe** [comment]
> $ touch this

**Comment by mirceaalexandru** [comment]
This is fixed as facebook auth is extracted as separate plugin - nherment/seneca-facebook-auth.

A PR will be also merged there.
