### ISSUE TITLE
Tests failing with Seneca@1.4.0

### ISSUE THREAD

**Issue by shanel262** [senecajs/seneca-auth#85]
The tests are failing on travis when using Seneca@1.4.0, although it works with 2.0.1 (except with Node@6).
https://travis-ci.org/senecajs/seneca-auth/builds/125576505

**Comment by shanel262** [comment]
Travis log error: 'seneca is already decorated with the property', the property is: 'si.use(require('seneca-entity'))'. This error only occurs when using Seneca@1.4.0. When using Seneca@2.0.1 and Node@6 a possible leak is detected with module 'Reflect'

**Comment by mihaidma** [comment]
solved: https://github.com/senecajs/seneca-auth/pull/92
